{
  "formatVersion": "1.1",
  "component": {
    "url": "../../timber/2.5.5-SNAPSHOT/timber-2.5.5-SNAPSHOT.module",
    "group": "timber.multiplatform.log",
    "module": "timber",
    "version": "2.5.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "timber-release.aar",
          "url": "timber-android-2.5.5-SNAPSHOT.aar",
          "size": 17262,
          "sha512": "655a5e7a169fcfc221f500fb852547e2e3dec224ac2020df984c9aaf4d05df907e8a28bbc37e95510b1bee63a8b9b91ba4984f5029a83a1763bb2ebc564acb60",
          "sha256": "dead814b6a531390cf6eb58158739f09c8d3797a4da5b17ff60596e7d204bfd3",
          "sha1": "5dca7bc00324e59d66ce2918229ac2d85c9b3c88",
          "md5": "6a397fa09b7ebefb1764c8386e3da729"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "timber-release.aar",
          "url": "timber-android-2.5.5-SNAPSHOT.aar",
          "size": 17262,
          "sha512": "655a5e7a169fcfc221f500fb852547e2e3dec224ac2020df984c9aaf4d05df907e8a28bbc37e95510b1bee63a8b9b91ba4984f5029a83a1763bb2ebc564acb60",
          "sha256": "dead814b6a531390cf6eb58158739f09c8d3797a4da5b17ff60596e7d204bfd3",
          "sha1": "5dca7bc00324e59d66ce2918229ac2d85c9b3c88",
          "md5": "6a397fa09b7ebefb1764c8386e3da729"
        }
      ]
    }
  ]
}
